"""Added tables

Revision ID: 51679e666321
Revises: 
Create Date: 2020-04-28 20:41:10.417974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51679e666321'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('countries')
    op.drop_index('ix_states_country_name', table_name='states')
    op.drop_index('ix_states_name', table_name='states')
    op.drop_table('states')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('states',
    sa.Column('name', sa.INTEGER(), nullable=False),
    sa.Column('country_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('total_infected', sa.INTEGER(), nullable=False),
    sa.Column('infected_today', sa.INTEGER(), nullable=False),
    sa.Column('total_deaths', sa.INTEGER(), nullable=False),
    sa.Column('deaths_today', sa.INTEGER(), nullable=False),
    sa.Column('total_recovered', sa.INTEGER(), nullable=False),
    sa.Column('recovered_today', sa.INTEGER(), nullable=False),
    sa.Column('active', sa.INTEGER(), nullable=False),
    sa.Column('critical', sa.INTEGER(), nullable=False),
    sa.Column('tests', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index('ix_states_name', 'states', ['name'], unique=False)
    op.create_index('ix_states_country_name', 'states', ['country_name'], unique=False)
    op.create_table('countries',
    sa.Column('name', sa.INTEGER(), nullable=False),
    sa.Column('flag', sa.VARCHAR(length=255), nullable=True),
    sa.Column('total_infected', sa.INTEGER(), nullable=False),
    sa.Column('infected_today', sa.INTEGER(), nullable=False),
    sa.Column('total_deaths', sa.INTEGER(), nullable=False),
    sa.Column('deaths_today', sa.INTEGER(), nullable=False),
    sa.Column('total_recovered', sa.INTEGER(), nullable=False),
    sa.Column('recovered_today', sa.INTEGER(), nullable=False),
    sa.Column('active', sa.INTEGER(), nullable=False),
    sa.Column('critical', sa.INTEGER(), nullable=False),
    sa.Column('tests', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###
